apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 4 
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: apache2:latest
        ports:
        - containerPort: 81